---
- name: VSCode - Exists
  stat:
    path: /usr/bin/code
  register: vscode_result

- name: VSCode
  apt:
    deb: https://go.microsoft.com/fwlink/?LinkID=760868
  when: vscode_result.stat.exists == False